#lang scribble/manual

@title{www.leafac.com}
@author{@author+email["Leandro Facchinetti" "me@leafac.com"]}

@emph{Source for Leandro Facchinetti’s personal website.}

@hyperlink["https://www.leafac.com"]{https://www.leafac.com}

@tabular[#:style 'boxed
         #:sep @hspace[1]
         #:row-properties '(bottom-border)
         `((, @bold{Documentation} , @hyperlink["https://www.leafac.com/software/www.leafac.com"]{https://www.leafac.com/software/www.leafac.com})
           (, @bold{License} , @hyperlink["https://gnu.org/licenses/gpl-3.0.txt"]{GNU General Public License Version 3})
           (, @bold{Code of Conduct} , @hyperlink["http://contributor-covenant.org/version/1/4/"]{Contributor Covenant v1.4.0})
           (, @bold{Source} , @hyperlink["https://git.leafac.com/www.leafac.com"]{https://git.leafac.com/www.leafac.com})
           (, @bold{Bug Reports} , @para{Write emails to @hyperlink["mailto:www.leafac.com@leafac.com"]|{www.leafac.com@leafac.com}|.})
           (, @bold{Contributions} , @para{Send @hyperlink["https://git-scm.com/docs/git-format-patch"]{patches} and @hyperlink["https://git-scm.com/docs/git-request-pull"]{pull requests} via email to @hyperlink["mailto:www.leafac.com@leafac.com"]|{www.leafac.com@leafac.com}|.}))]

@section[#:tag "setup"]{Setup}

The website is a static webpage generated by @hyperlink["http://pollenpub.com/"]{Pollen}, a @hyperlink["https://racket-lang.org/"]{Racket} library. Run the following to install the dependencies:

@nested[#:style 'code-inset @verbatim{
  $ raco setup
         }]

Then start the preview server with:

@nested[#:style 'code-inset @verbatim{
  $ raco pollen start source/
         }]