name: Main
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: |
          gem install github-pages html-proofer
          jekyll build
          htmlproofer --assume-extension ./_site
