name: Main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install Gems
        run: gem install github-pages html-proofer
      - name: Build
        run: jekyll build
      - name: HTMLProofer
        run: htmlproofer --assume-extension ./_site
